name: Cache build container(s)
# New branches will only use caches from the default branch (`main`)
# https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build charm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          bootstrap-options: "--agent-version 2.9.29"
      - name: Cache `charmcraft pack` LXC instance(s)
        id: container-cache
        uses: actions/cache@v3
        with:
          path: ~/ga-cache/**
          key: ${{ runner.os }}-${{ hashFiles('charmcraft.yaml') }}
      - if: ${{ steps.container-cache.outputs.cache-hit }}
        name: Import cached container(s)
        run: |
          # Project setup copied from https://github.com/canonical/craft-providers/blob/20d154bb8fa9868a678c5621f124a02e2b9e72ad/craft_providers/lxd/project.py#L26
          lxc project create charmcraft
          lxc --project default profile show default | lxc --project charmcraft profile edit default
          charm_repository_directory_inode=$(stat --format "%i" .)
          for container_tarball in ~/ga-cache/*
          do
            lxc --project charmcraft import $container_tarball
            container_name_without_inode=$(basename --suffix .tar.gz $container_tarball)
            # Replace placeholder text "INODE" with inode
            container_name_with_inode=$(echo $container_name_without_inode | sed "s/INODE/$charm_repository_directory_inode/")
            lxc --project charmcraft move $container_name_without_inode $container_name_with_inode
          done
      - name: Pack charm
        run: charmcraft pack
      - name: Export `charmcraft pack` container(s) to cache
        run: |
          mkdir -p ~/ga-cache
          charm_repository_directory_inode=$(stat --format "%i" .)
          for container_name_with_inode in $(lxc --project charmcraft list --columns n --format csv)
          do
            # Replace inode with placeholder text "INODE"
            container_name_without_inode=$(echo $container_name_with_inode | sed "s/$charm_repository_directory_inode/INODE/")
            lxc --project charmcraft move $container_name_with_inode $container_name_without_inode
            # Use GitHub actions/cache compression
            lxc --project charmcraft export --optimized-storage --compression none $container_name_without_inode ~/ga-cache/$container_name_without_inode.tar.gz
          done
